name: Push exporter

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./exporter
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  push-docker:
    needs: release
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./exporter
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: r2wireless
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Push 
        uses: docker/build-push-action@v5
        with:
          context: ./exporter
          platforms: linux/arm64
          push: true
          tags: r2wireless/redis-queues-exporter:${{ env.VERSION }}
        