name: Push exporter

on: [push]

jobs:
  push-docker:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./exporter
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: r2wireless
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Push 
        uses: docker/build-push-action@v5
        with:
          context: ./exporter
          platforms: linux/arm64
          push: true
          tags: r2wireless/redis-queues-exporter:master
        