name: Push exporter

on: [push]

jobs:
  push-docker:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./exporter
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/redis-queues-exporter:master
        