name: Push exporter

on: [push]

jobs:
  push-docker:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./exporter
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: r2wireless
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push 
        uses: docker/build-push-action@v5
        with:
          context: ./exporter
          file: ./Dockerfile
          push: true
          tags: r2wireless/redis-queues-exporter:master
        